import { Link } from 'react-router-dom';
import './Home.css';

export default function Home() {
  return (
    <div className="home">
      <section className="hero">
        <div className="hero-content">
          <h1>Capillary Documentation Assistant</h1>
          <p className="subtitle">Get instant, accurate answers about Capillary's platform, documentation and APIs</p>
          <Link to="/chat" className="cta-button">
            Start a conversation <span className="arrow">→</span>
          </Link>
        </div>
      </section>

      <section className="features">
        <h2 className="section-title">Key Features Implemented</h2>
        <div className="feature-cards">
          <div className="feature-card">
            <div className="icon-circle">
              <svg className="icon" viewBox="0 0 24 24">
                <path d="M14 2H6c-1.1 0-2 .9-2 2v16c0 1.1.9 2 2 2h12c1.1 0 2-.9 2-2V8l-6-6zM6 20V4h7v5h5v11H6z"/>
              </svg>
            </div>
            <h3>Web Scrapping</h3>
            <p>Scrapped relevant information from the CapillaryTech documentation.</p>
          </div>
          <div className="feature-card">
            <div className="icon-circle">
              <svg className="icon" viewBox="0 0 24 24">
                <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-6h2v6zm0-8h-2V7h2v2z"/>
              </svg>
            </div>
            <h3>RAG Based Q/A</h3>
            <p>Implemented RAG system that can effectively respond to queries using retrieved data.</p>
          </div>
          <div className="feature-card">
            <div className="icon-circle">
              <svg className="icon" viewBox="0 0 24 24">
                <path d="M12 3c-4.97 0-9 3.185-9 7.115 0 2.557 1.522 4.82 3.889 6.115l-.78 2.77 3.116-1.65c.88.275 1.823.425 2.775.425 4.97 0 9-3.186 9-7.115C21 6.186 16.97 3 12 3z"/>
              </svg>
            </div>
            <h3>ChatBot using LLM</h3>
            <p>Quick answers are generated by LLM using the most relevant document chunks.</p>
          </div>
        </div>
      </section>

      <section className="how-it-works">
        <h2 className="section-title">How It Works</h2>
        <div className="steps">
          <div className="step">
            <div className="step-number">1</div>
            <div className="step-content">
              <h3>Ask Your Question</h3>
              <p>Type your query related to Capillary documentation in the chat box.</p>
            </div>
          </div>
          <div className="step">
            <div className="step-number">2</div>
            <div className="step-content">
              <h3>Smart Search</h3>
              <p>The system finds the most relevant info from the docs using sementic search.</p>
            </div>
          </div>
          <div className="step">
            <div className="step-number">3</div>
            <div className="step-content">
              <h3>Get Instant Answers</h3>
              <p>You get a clear, accurate response generated from the documentation itself.</p>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}